name: Launcher Build
on:
  push:
    branches: [ master ]

# TRÈS IMPORTANT : On donne les pleins droits pour écrire les releases et les packages
permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest, windows-2022]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      # Compilation et publication (va créer un Draft dans vos Releases)
      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build -- --publish always
        shell: bash

      # SÉCURITÉ ABSOLUE : Sauvegarde les fichiers dans l'onglet "Actions" 
      # pour pouvoir les télécharger directement sans passer par les Releases.
      - name: Sauvegarder les exécutables locaux (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: Atheris-Launcher-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.deb
            dist/*.AppImage
          if-no-files-found: ignore