name: Launcher Build
on:
  push:
    branches: [ master ]

permissions:
  contents: write
  packages: write

jobs:
  build-launcher:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-latest, windows-2022]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      # On utilise 'npm run build' qui contient bien '--build=platform' pour réveiller ton build.js.
      # L'ajout des flags --win, --linux et --mac force electron-builder (appelé par ton script)
      # à générer le bon format selon l'OS de la machine virtuelle.
      - name: Build Launcher (Windows)
        if: matrix.os == 'windows-2022'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTODISCOVER: false
        run: npm run build -- --win
        shell: bash

      - name: Build Launcher (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build -- --linux
        shell: bash

      - name: Build Launcher (Mac)
        if: matrix.os == 'macos-14'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTODISCOVER: false
        run: npm run build -- --mac
        shell: bash

      # Ton build.js ayant la propriété "directories: { output: 'dist' }",
      # on cible précisément le dossier dist/ pour récupérer les exécutables.
      - name: Sauvegarder l'exécutable (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: Atheris-Launcher-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
            dist/*.AppImage
          if-no-files-found: warn